# Generated by Django 5.2.1 on 2025-05-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0005_juego_imagen'),
        ('jugadores', '0019_alter_participaciones_detalles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PROXIMAMENTE', 'Próximamente'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='PROXIMAMENTE', max_length=12)),
                ('max_participantes', models.PositiveIntegerField(default=0)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to='juegos.juego')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_torneo', to='jugadores.jugadores')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='torneos.torneo')),
            ],
            options={
                'unique_together': {('torneo', 'jugador')},
            },
        ),
    ]
