# Generated by Django 5.2.1 on 2025-05-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0018_remove_jugadores_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participaciones',
            name='detalles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
