# Generated by Django 5.2.1 on 2025-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_alter_juego_nombre_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.CharField(blank=True, default='img/juegos/default_game.png', max_length=255, null=True),
        ),
    ]
